# ===============================================================
# SPECIFICKA KONFIGURACE PRO LOKALNI VYVOJ (PROFIL: local)
# ===============================================================

# --- DATABAZE & HIBERNATE ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 1. Změň 'update' na 'create' pro první spuštění, aby se tabulky vynutily
# Jakmile se aplikace jednou rozběhne, můžeš to vrátit na 'update'
spring.jpa.hibernate.ddl-auto=update

# 3. Vypnutí Flyway ponecháme, pokud nechceš psát migrační skripty ručně
spring.flyway.enabled=false

# --- ROZSIRENE LOGOVANI ---
logging.level.org.springframework.core.env=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Zobrazi hodnoty v SQL dotazech misto ?
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# App logy
logging.level.com.checkfood=DEBUG
logging.level.org.springframework.security=DEBUG

# --- DEVTOOLS ---
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# --- EMAIL FIX (SSL) ---
# Obchazi kontrolu certifikatu na localhostu
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.debug=true

# --- FILE UPLOAD ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.storage.public-dir=./uploads/public
app.storage.private-dir=./uploads/private

overture.release.path=s3://overturemaps-us-west-2/release/2026-*/theme=places/type=place/*.parquet