spring.datasource.url=jdbc:postgresql://34.134.216.137:5432/checkfood-db
spring.datasource.username=checkfood-db
spring.datasource.password=123heslo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Nepovinné, ale užitečné
spring.sql.init.mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true