/// Cuisine category for a restaurant listing.
enum CuisineType {
  ITALIAN,
  CZECH,
  ASIAN,
  VIETNAMESE,
  INDIAN,
  FRENCH,
  MEXICAN,
  AMERICAN,
  MEDITERRANEAN,
  JAPANESE_SUSHI,
  BURGER,
  PIZZA,
  VEGAN_VEGETARIAN,
  INTERNATIONAL,
  STREET_FOOD,
  KEBAB,
  CAFE_DESSERT,
  OTHER;

  String get displayName => switch (this) {
    CuisineType.ITALIAN => 'Italská',
    CuisineType.CZECH => 'Česká',
    CuisineType.ASIAN => 'Asijská',
    CuisineType.VIETNAMESE => 'Vietnamská',
    CuisineType.INDIAN => 'Indická',
    CuisineType.FRENCH => 'Francouzská',
    CuisineType.MEXICAN => 'Mexická',
    CuisineType.AMERICAN => 'Americká',
    CuisineType.MEDITERRANEAN => 'Středomořská',
    CuisineType.JAPANESE_SUSHI => 'Sushi a japonská',
    CuisineType.BURGER => 'Burgery',
    CuisineType.PIZZA => 'Pizza',
    CuisineType.VEGAN_VEGETARIAN => 'Vegetariánská a veganská',
    CuisineType.INTERNATIONAL => 'Mezinárodní',
    CuisineType.STREET_FOOD => 'Street food',
    CuisineType.KEBAB => 'Kebab',
    CuisineType.CAFE_DESSERT => 'Kavárna a dezerty',
    CuisineType.OTHER => 'Ostatní',
  };
}
